version: '3.8'

services:
  ngram_api:
    build:
      context: ./scr/back/
      dockerfile: back.dockerfile
    ports:
      - "8005:8000"
    

  streamlit_ngram_app:
    build:
      context: ./scr/front
      dockerfile: front.dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - ngram_api
